import { useState } from 'react'
import { eggCycles } from '../data/hatchingResources'
import { pokemonMeta } from '../data/pokemonMeta'
const species=Object.keys(eggCycles).sort((a,b)=>pokemonMeta[a].dex-pokemonMeta[b].dex)
const rules=[
 ['Offspring and special pairs',<>The offspring normally comes from the female’s evolution family. With Ditto, use the other parent’s family.<p>Nidoran♀ can produce Nidoran♀ or Nidoran♂. Illumise can produce Illumise or Volbeat. Each split is approximately 50/50. Nidorina and Nidoqueen cannot breed.</p><p>For Azurill, breed Marill or Azumarill with a parent holding Sea Incense. Without it, the Egg contains Marill. For Wynaut, a Wobbuffet parent pair needs Lax Incense on either parent; otherwise the Egg contains Wobbuffet.</p></>],
 ['IV inheritance',<>The Egg starts with random IVs from 0 to 31. Emerald then makes three inheritance selections, choosing either parent for each selected stat.<p>A bug can select the same stat more than once, so three distinct inherited stats are not guaranteed. HP and Defense have lower selection chances. The final selection overwrites an earlier selection of the same stat.</p><p>EVs are not inherited. Power items and Destiny Knot inheritance mechanics are not available in Emerald.</p></>],
 ['Nature and Everstone',<>Without Everstone, nature is random. An Everstone held by the female gives approximately a 50% chance to copy her nature.<p>When Ditto is a parent, Ditto takes priority: give the Everstone to Ditto. An Everstone on the other parent does not supply the nature in that pairing. A male’s Everstone does not pass nature in an ordinary male/female pair.</p></>],
 ['Abilities, gender, and shininess',<>Abilities are not inherited from a parent in Emerald. The offspring’s personality chooses its ability slot; a species with two ordinary abilities has roughly equal chances of either. Hidden Abilities do not exist here.<p>Gender follows the offspring species’ gender ratio. Shiny parents do not increase the offspring’s shiny chance; Emerald has no Masuda Method. Day Care Eggs hatch at level 5 in a Poké Ball.</p></>],
 ['Move inheritance',<>The Egg begins with its starting level-up moves. It can then receive egg moves known by the father, TM/HM moves known by the father that the offspring can learn, and level-up moves known by both parents.<p>The father must still know the move when the Egg is received. A tutor move is not automatically inherited: it must also qualify under an inheritance rule. With Ditto and a male or genderless partner, the non-Ditto parent supplies father moves.</p><p>Only four moves fit. Additional inherited moves replace earlier moves. Parents gain levels in the Day Care and can forget moves as they learn new ones, so check their moves before collecting Eggs.</p></>],
 ['Producing Eggs',<>The Day Care is on Route 117. Compatible parents are checked for an Egg about every 256 steps when no Egg is waiting.<p>Same species and different full Original Trainer IDs: about 70% per check. Same species/same ID or different species/different IDs: about 50%. Different species/same ID: about 20%. A Ditto pair uses 50% for different IDs and 20% for the same ID.</p><p>These are chances per check, not per step. Incompatible pairs never produce Eggs. Picking up or declining an Egg starts the next production cycle.</p></>],
 ['Hatching and faster cycling',<>Eggs carry a species-specific cycle counter. Emerald normally reduces it by one at each hatch check, about every 256 steps.<p>A non-Egg party Pokémon with Flame Body or Magma Armor makes the counter fall by two instead. One helper is enough; multiple helpers do not stack. Keep the Eggs in your party and cycle to accumulate steps.</p><p>An Egg hatches on a check after its counter reaches zero. Shared counter timing, collecting Eggs, and other Eggs hatching can affect exact step counts, so the species cycle value is more reliable than an exact walking-distance promise.</p></>],
]
export default function BreedingRules(){
 const [id,setId]=useState('1')
 return <article className="resource-species"><div className="resource-species-hero"><span>EMERALD · BREEDING GUIDE</span><h2>Inheritance & Hatching</h2></div><section><p className="resource-note">Rules for Pokémon Emerald. Open a topic to read its details.</p><div className="resource-trainer-list">{rules.map(([title,body])=><details className="resource-trainer-card" key={title}><summary><strong>{title}</strong><b aria-hidden="true">⌄</b></summary><div className="resource-egg-route">{body}</div></details>)}</div></section><section><h3>Species egg cycles</h3><label className="resources-search">Species<select className="resource-cycle-select" aria-label="Hatching species" value={id} onChange={e=>setId(e.target.value)}>{species.map(key=><option key={key} value={key}>#{String(pokemonMeta[key].dex).padStart(3,'0')} {pokemonMeta[key].name}</option>)}</select></label><div className="resource-hp-result" aria-live="polite"><span>{pokemonMeta[id].name} · Initial egg cycles</span><strong>{eggCycles[id]}</strong></div><p className="resource-note">This is a species data value, not a guarantee the species can produce an Egg. For example, legendary and other Undiscovered Pokémon cannot breed.</p></section><p className="resource-note">Sources: <a href="https://github.com/pret/pokeemerald/blob/master/src/daycare.c" target="_blank" rel="noreferrer">Day Care and inheritance</a>, <a href="https://github.com/pret/pokeemerald/blob/master/src/egg_hatch.c" target="_blank" rel="noreferrer">hatching abilities</a>, and <a href="https://github.com/pret/pokeemerald/blob/master/src/data/pokemon/species_info.h" target="_blank" rel="noreferrer">species egg cycles</a>.</p></article>
}
