import { useState } from 'react'
import { pokemonMeta } from '../data/pokemonMeta'
import { eggGroups } from '../data/breedingResources'
import { eggGroupNames, speciesGenders, partnerGenders } from '../utils/breeding'
const species=Object.entries(pokemonMeta).filter(([id,m])=>eggGroups[id]&&m.dex>=1&&m.dex<=386).sort((a,b)=>a[1].dex-b[1].dex)
export default function BreedingGuide({ initialParent, onPokemon }){
 const [id,setId]=useState(initialParent?.id??'1')
 const [gender,setGender]=useState(initialParent?.gender??speciesGenders(id)[0])
 const [query,setQuery]=useState('')
 const groups=eggGroups[id],meta=pokemonMeta[id]
 const partners=species.map(([partnerId,m])=>({id:partnerId,meta:m,genders:partnerGenders(id,gender,partnerId)})).filter(p=>p.genders.length&&p.meta.name.toLowerCase().includes(query.toLowerCase()))
 return <article className="resource-species"><div className="resource-species-hero"><span>EMERALD · BREEDING GUIDE</span><h2>Breeding Partners</h2></div>
 <section><div className="resource-iv-inputs"><label>Parent species<select aria-label="Parent species" value={id} onChange={e=>{setId(e.target.value);setGender(speciesGenders(e.target.value)[0])}}>{species.map(([key,m])=><option key={key} value={key}>#{String(m.dex).padStart(3,'0')} {m.name}</option>)}</select></label><label>Parent gender<select aria-label="Parent gender" value={gender} onChange={e=>setGender(e.target.value)}>{speciesGenders(id).map(g=><option key={g}>{g}</option>)}</select></label></div><h3>{meta.name} egg groups</h3><div className="resource-types">{groups.map(group=><span key={group}>{eggGroupNames[group]}</span>)}</div>
 {groups.includes('NO_EGGS_DISCOVERED')?<p className="resource-note">This Pokémon cannot produce Eggs, even with Ditto. Babies must evolve into a breedable species first.</p>:groups.includes('DITTO')?<p className="resource-note">Ditto breeds with eligible Pokémon of any gender, including genderless Pokémon. Two Ditto cannot produce an Egg.</p>:gender==='Genderless'?<p className="resource-note">This genderless Pokémon can breed only with Ditto.</p>:<p className="resource-note">Partners need the opposite gender and at least one shared egg group. Ditto is also compatible.</p>}
 </section><section><h3>Compatible partners</h3><label className="resources-search">Search partners<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Pokémon…"/></label><p className="resource-note" aria-live="polite">{partners.length} compatible species for {gender.toLowerCase()} {meta.name}. The required partner gender is shown below. This lists Gen I–III compatibility; some Pokémon require trading into Emerald.</p><div className="resource-pokemon-grid">{partners.map(p=><button key={p.id} onClick={()=>onPokemon([p.id,p.meta],{id,gender})}><span>#{String(p.meta.dex).padStart(3,'0')}</span><img loading="lazy" src={`${import.meta.env.BASE_URL}sprites/emerald/${p.meta.dex}.png`} alt=""/><strong>{p.meta.name}</strong><small>{p.genders.join(' or ')}</small></button>)}</div>{!partners.length&&<p className="resource-empty">No results.</p>}</section>
 <section><h3>Day Care basics</h3><p>Use the Pokémon Day Care on Route 117. Sharing an egg group is enough; partners do not have to be the same species. Original Trainer IDs and species affect how quickly compatible parents produce Eggs.</p><p>The Fairy egg group is a breeding category, not a Pokémon type in Emerald. Undiscovered Pokémon cannot breed. Genderless Pokémon outside that group require Ditto.</p><p>This finder checks whether the pair can breed. It does not predict the offspring, inherited moves, or stats. Egg moves, inheritance, incense exceptions, and hatching mechanics will follow.</p></section><p className="resource-note">Sources: <a href="https://github.com/pret/pokeemerald/blob/master/src/data/pokemon/species_info.h" target="_blank" rel="noreferrer">Emerald egg groups</a> and <a href="https://github.com/pret/pokeemerald/blob/master/src/daycare.c" target="_blank" rel="noreferrer">Day Care compatibility rules</a>.</p></article>
}
