import { useState } from 'react'
import { evYields } from '../data/evResources'
import { pokemonMeta } from '../data/pokemonMeta'
import { locationResources } from '../data/locationResources'
import { ivStats } from '../utils/ivCalculator'
const labels=Object.fromEntries(ivStats)
const yieldText=yields=>ivStats.filter(([key])=>yields[key]>0).map(([key,label])=>`${yields[key]} ${label}`).join(' · ')
export default function EVGuide({ initialStat='hp', onPokemon, onLocation }){
 const [stat,setStat]=useState(initialStat??'hp')
 const [search,setSearch]=useState('')
 const [pure,setPure]=useState(true)
 const [brace,setBrace]=useState(false)
 const [pokerus,setPokerus]=useState(false)
 const multiplier=(brace?2:1)*(pokerus?2:1)
 const pokemon=Object.entries(pokemonMeta).filter(([id,meta])=>evYields[id]?.[stat]>0&&meta.name.toLowerCase().includes(search.toLowerCase())&&(!pure||Object.values(evYields[id]).reduce((a,b)=>a+b,0)===evYields[id][stat])).sort((a,b)=>a[1].dex-b[1].dex)
 const spots=locationResources.flatMap(location=>location.methods.map(method=>{
 const targets=method.encounters.filter(mon=>evYields[mon.species]?.[stat]>0&&Object.values(evYields[mon.species]).reduce((a,b)=>a+b,0)===evYields[mon.species][stat])
 return {location,method:method.name,targets,rate:targets.reduce((sum,mon)=>sum+mon.rate,0),level:Math.min(...targets.map(mon=>mon.min))}
 })).filter(s=>s.rate>0&&!s.location.name.includes('Safari')).sort((a,b)=>b.rate-a.rate||a.level-b.level||a.location.name.localeCompare(b.location.name)).filter((s,i,all)=>all.findIndex(other=>other.location.id===s.location.id)===i).slice(0,5)
 return <article className="resource-species"><div className="resource-species-hero"><span>EMERALD · TRAINING GUIDE</span><h2>EV Training</h2></div>
 <section><h3>Choose a stat</h3><label className="resource-type-filter">Training stat<select aria-label="Training stat" value={stat} onChange={e=>setStat(e.target.value)}>{ivStats.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><div className="resource-ev-options"><label><input type="checkbox" checked={brace} onChange={e=>setBrace(e.target.checked)}/>Macho Brace</label><label><input type="checkbox" checked={pokerus} onChange={e=>setPokerus(e.target.checked)}/>Pokérus</label></div><p className="resource-note">Battle EV multiplier: {multiplier}×. Yields below include these bonuses, before the 255 per-stat and 510 total limits.</p></section>
 <section><h3>{labels[stat]} training locations</h3><p className="resource-note">High target encounter rates, with lower-level spots first when rates tie. Rates are conditional on an encounter using that method. Defeat only the listed targets to keep your training focused; other encounters can give different EVs. These are encounter-based suggestions, not a measure of training speed.</p><div className="resource-move-list">{spots.map(spot=><button key={spot.location.id} onClick={()=>onLocation(spot.location,stat)}><div><strong>{spot.location.name} · {spot.rate}% targets</strong><small>{spot.method}<br/>{spot.targets.map(mon=>`${pokemonMeta[mon.species].name}: ${evYields[mon.species][stat]*multiplier} EV${evYields[mon.species][stat]*multiplier===1?'':'s'} · Lv. ${mon.min===mon.max?mon.min:`${mon.min}–${mon.max}`}`).join(' / ')}</small></div><b aria-hidden="true">›</b></button>)}</div></section>
 <section><h3>Pokémon EV yields</h3><label className="resources-search">Search Pokémon<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try Whismur…"/></label><label className="resource-ev-options"><input type="checkbox" checked={pure} onChange={e=>setPure(e.target.checked)}/>Only Pokémon that give this stat alone</label><p className="resource-note">{pokemon.length} species · All Gen I–III species; not all are catchable in Emerald.</p><div className="resource-encounter-list">{pokemon.map(([id,meta])=><button key={id} onClick={()=>onPokemon([id,meta],stat)}><img loading="lazy" src={`${import.meta.env.BASE_URL}sprites/emerald/${meta.dex}.png`} alt=""/><div><strong>{meta.name}</strong><small>{yieldText(Object.fromEntries(Object.entries(evYields[id]).map(([key,value])=>[key,value*multiplier])))} EVs</small></div><b aria-hidden="true">›</b></button>)}</div></section>
 <section><h3>Training basics</h3><p>Emerald allows 255 EVs in one stat and 510 overall. The stat formula uses EVs divided by four, rounded down. At level 100, 4 EVs contribute one stat point before nature; 252 is the last useful multiple of four below 255.</p><p>Macho Brace doubles battle EVs and halves Speed while held in battle. Pokérus doubles battle EVs, even after it stops being contagious. Together they give 4× EVs. Exp. Share recipients also receive the defeated Pokémon’s full EV yield; it is not split.</p><p>EVs gained in battle need a stat recalculation to appear in the summary. Level up or deposit and withdraw the Pokémon. At level 100 in Emerald, Pokémon do not gain battle EVs.</p></section>
 <section><h3>Vitamins</h3><p>Add up to 10 EVs in their stat, stopping at 100 EVs in that stat or the 510 total limit. Use them before battle training. Macho Brace and Pokérus do not multiply vitamin gains.</p><table className="resource-nature-table"><thead><tr><th>Stat</th><th>Vitamin</th><th>EV-reducing berry</th></tr></thead><tbody>{[['HP','HP Up','Pomeg'],['Attack','Protein','Kelpsy'],['Defense','Iron','Qualot'],['Sp. Attack','Calcium','Hondew'],['Sp. Defense','Zinc','Grepa'],['Speed','Carbos','Tamato']].map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={i}>{cell}</td>)}</tr>)}</tbody></table></section>
 <section><h3>Resetting EVs</h3><p>Each listed berry removes 10 EVs from its stat, down to zero, and can increase friendship. In Emerald, a berry does not first reset a stat above 100 EVs to 100. From 255 EVs, it takes 26 berries to reach zero.</p></section>
 <p className="resource-note">Sources: <a href="https://github.com/pret/pokeemerald/blob/master/src/data/pokemon/species_info.h" target="_blank" rel="noreferrer">species yields</a>, <a href="https://github.com/pret/pokeemerald/blob/master/src/data/wild_encounters.json" target="_blank" rel="noreferrer">encounters</a>, and <a href="https://github.com/pret/pokeemerald/blob/master/src/pokemon.c" target="_blank" rel="noreferrer">EV and item-effect logic</a>.</p></article>
}
