import { useState } from 'react'
import BreedingRules from './BreedingRules'
import EggMovesGuide from './EggMovesGuide'
import BreedingGuide from './BreedingGuide'
import MoveTutors from './MoveTutors'
import EVGuide from './EVGuide'
export default function GuidesBrowser({ onBack, onPokemon, onLocation, initialStat, initialEgg, onEggMove, onEggPokemon, initialParent, onBreedingPokemon, initialTutor, onTutorPokemon, onTutorMove }){
 const [guide,setGuide]=useState(initialEgg?'eggs':initialParent?'breeding':initialTutor?'tutors':initialStat?'ev':null)
 return <div className="resources-page"><button className="resources-back" onClick={guide?()=>setGuide(null):onBack}>← Back</button>{guide==='rules'?<BreedingRules/>:guide==='eggs'?<EggMovesGuide initialEgg={initialEgg} onMove={onEggMove} onPokemon={onEggPokemon}/>:guide==='breeding'?<BreedingGuide initialParent={initialParent} onPokemon={onBreedingPokemon}/>:guide==='tutors'?<MoveTutors initialTutor={initialTutor} onPokemon={onTutorPokemon} onMove={onTutorMove}/>:guide?<EVGuide initialStat={initialStat} onPokemon={onPokemon} onLocation={onLocation}/>:<><div className="resource-list-heading"><h2>Guides</h2></div><div className="resources-categories"><button onClick={()=>setGuide('ev')}><h2>EV Training</h2><p>Pokémon yields, training locations, and Emerald training mechanics.</p><b>Open guide →</b></button><button onClick={()=>setGuide('tutors')}><h2>Move Tutors</h2><p>Locations, BP costs, and compatible Pokémon.</p><b>Open guide →</b></button><button onClick={()=>setGuide('breeding')}><h2>Breeding Partners</h2><p>Egg groups and compatible partners by species and gender.</p><b>Open finder →</b></button><button onClick={()=>setGuide('eggs')}><h2>Egg Moves</h2><p>Egg moves, compatible fathers, and breeding chains.</p><b>Open guide →</b></button><button onClick={()=>setGuide('rules')}><h2>Inheritance & Hatching</h2><p>IVs, Everstone, special offspring, move inheritance, and egg cycles.</p><b>Open guide →</b></button></div><p className="resource-note">Battle Frontier guides will follow.</p></>}</div>
}
