import { useState } from 'react'
import { locationResources } from '../data/locationResources'
import { shopLocations } from '../data/locationShops'
import { itemLocations } from '../data/locationItems'
import { itemResources, machineResources } from '../data/itemResources'
import { itemNames, moveNames } from '../data/emeraldData'
import { trainerLocations } from '../data/trainerResources'
import { pokemonMeta } from '../data/pokemonMeta'
const merged=new Map(locationResources.map(location=>[location.id,{...location,trainers:[],items:[]}]))
for(const location of trainerLocations) merged.set(location.id,{...(merged.get(location.id)??{methods:[],items:[]}),...location})
for(const location of itemLocations) merged.set(location.id,{...(merged.get(location.id)??{methods:[],trainers:[]}),...location})
for(const location of shopLocations) merged.set(location.id,{...(merged.get(location.id)??{methods:[],trainers:[],items:[]}),...location})
for(const location of merged.values()){location.shops??=[];location.trees??=[]}
const locations=[...merged.values()].sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}))
function itemEntry(found){const machine=found.code?machineResources.find(m=>m.code===found.code):null;return machine?{...machine,machine:true,name:moveNames[machine.moveId]}:{...itemResources[found.item],id:String(found.item),name:itemNames[found.item]??itemResources[found.item].name}}
const methods=[...new Set(locations.flatMap(location=>location.methods.map(m=>m.name)))]
export default function LocationsBrowser({ onBack, onPokemon, onItem, initialLocation, onDetailBack }) {
 const [search,setSearch]=useState('')
 const [method,setMethod]=useState('all')
 const [selected,setSelected]=useState(initialLocation?(merged.get(initialLocation.id)??initialLocation):null)
 const matches=locations.filter(location=>location.name.toLowerCase().includes(search.trim().toLowerCase())&&(method==='all'||(method==='shops'&&location.shops.length>0)||(method==='trees'&&location.trees.length>0)||(method==='items'&&location.items.length>0)||(method==='trainers'&&location.trainers.length>0)||location.methods.some(m=>m.name===method)))
 return <div className="resources-page">
 <button className="resources-back" onClick={selected?(onDetailBack??(()=>setSelected(null))):onBack}>← Back</button>
 {selected?<article className="resource-species">
 <div className="resource-species-hero"><span>EMERALD · HOENN</span><h2>{selected.name}</h2></div>
 {selected.methods.length>0&&<p className="resource-note">Rates show the chance of each species once an encounter occurs using that method. Levels show the full range across encounter slots. Lead abilities and special encounter rules can change results.</p>}
 {selected.methods.map(table=><section key={table.name}><h3>{table.name}</h3><div className="resource-encounter-list resource-wild-encounters">{table.encounters.map(mon=>{const meta=pokemonMeta[mon.species];return <button key={mon.species} onClick={()=>onPokemon([String(mon.species),meta],selected)}><img loading="lazy" src={`${import.meta.env.BASE_URL}sprites/emerald/${meta.dex}.png`} alt=""/><div><strong>{meta.name}</strong><small>Lv. {mon.min===mon.max?mon.min:`${mon.min}–${mon.max}`}</small></div><b>{mon.rate}%</b></button>})}</div></section>)}
 {selected.trainers?.length>0&&<section><h3>Trainers · {selected.trainers.length}</h3><p className="resource-note">Initial teams are shown. Prize money is the base reward before Amulet Coin. Separate trainers fought together contribute their own rewards.</p><div className="resource-trainer-list">{selected.trainers.map(trainer=><details className="resource-trainer-card" key={trainer.id}><summary><div><strong>{trainer.name}</strong><small>{trainer.class} · {trainer.double?'Double battle':'Single battle'}</small></div><b>₽ {trainer.prize.toLocaleString()}</b></summary><div className="resource-encounter-list">{trainer.team.map((mon,index)=>{const meta=pokemonMeta[mon.species];return <button key={index} onClick={()=>onPokemon([String(mon.species),meta],selected)}><img loading="lazy" src={`${import.meta.env.BASE_URL}sprites/emerald/${meta.dex}.png`} alt=""/><div><strong>{meta.name}</strong><small>Lv. {mon.level}</small></div><b aria-hidden="true">›</b></button>})}</div></details>)}</div></section>}
 {selected.items?.length>0&&<section><h3>Items · {selected.items.length}</h3><p className="resource-note">Gift and reward requirements vary with story progress, trades, or events. Map tiles are shown for pickups and hidden items; they count from the map’s top-left corner.</p><div className="resource-move-list">{selected.items.map((found,index)=>{const machine=found.code?machineResources.find(m=>m.code===found.code):null;const entry=machine?{...machine,machine:true,name:moveNames[machine.moveId]}:{...itemResources[found.item],id:String(found.item),name:itemNames[found.item]??itemResources[found.item].name};return <button key={index} onClick={()=>onItem(entry,selected)}><div><strong>{machine?`${machine.code} · ${entry.name}`:entry.name}{found.quantity>1?` ×${found.quantity}`:''}</strong><small>{found.kind}{found.x!=null?` · Tile (${found.x}, ${found.y})`:''}</small></div><b aria-hidden="true">›</b></button>})}</div></section>}
 {selected.shops.length>0&&<section><h3>Shops</h3><p className="resource-note">Prices are per item in Emerald. Separate inventories represent different counters or stock that changes with story progress.</p>{selected.shops.map((shop,index)=><div key={index}><h4>{shop.name}</h4><div className="resource-move-list">{shop.items.map(found=>{const entry=itemEntry(found);return <button key={found.item} onClick={()=>onItem(entry,selected)}><div><strong>{entry.machine?`${entry.code} · ${entry.name}`:entry.name}</strong></div><b>₽ {found.price.toLocaleString()}</b></button>})}</div></div>)}</section>}
 {selected.trees.length>0&&<section><h3>Berry Trees · {selected.trees.length}</h3><p className="resource-note">These are the berries planted at the start of a new game. Harvesting and replanting can change them. Tile coordinates count from the map’s top-left corner.</p><div className="resource-move-list">{selected.trees.map((tree,index)=>{const entry=itemEntry(tree);return <button key={index} onClick={()=>onItem(entry,selected)}><div><strong>{entry.name}</strong><small>Initially planted · Tile ({tree.x}, {tree.y})</small></div><b aria-hidden="true">›</b></button>})}</div></section>}
 <p className="resource-note">These are the standard wild encounter tables. Gift Pokémon, static encounters, swarms, and special encounters such as Feebas tiles are not included yet. Rematch teams, dynamically selected battles, decoration shops, special exchanges, and variable or shared-script item rewards are not included yet.</p>
 <p className="resource-note">Source: <a href="https://github.com/pret/pokeemerald/blob/master/src/data/wild_encounters.json" target="_blank" rel="noreferrer">Emerald encounter tables</a> and <a href="https://github.com/pret/pokeemerald/blob/master/src/data/trainers.h" target="_blank" rel="noreferrer">trainer data</a>. Items come from <a href="https://github.com/pret/pokeemerald/tree/master/data/maps" target="_blank" rel="noreferrer">map events and scripts</a>; initial berries use <a href="https://github.com/pret/pokeemerald/blob/master/data/scripts/new_game.inc" target="_blank" rel="noreferrer">new-game planting data</a>.</p>
 </article>:<>
 <div className="resource-list-heading"><h2>Explore Hoenn</h2><span>{matches.length} locations</span></div>
 <label className="resources-search"><span>Search locations</span><input type="search" placeholder="Try Route 102 or Granite Cave…" value={search} onChange={e=>setSearch(e.target.value)}/></label>
 <label className="resource-type-filter">Method<select value={method} onChange={e=>setMethod(e.target.value)}><option value="all">All locations</option><option value="trainers">With trainers</option><option value="items">With items</option><option value="shops">With shops</option><option value="trees">With berry trees</option>{methods.map(name=><option key={name}>{name}</option>)}</select></label>
 <div className="resource-move-list">{matches.map(location=><button key={location.id} onClick={()=>setSelected(location)}><div><strong>{location.name}</strong><small>{[...location.methods.map(m=>m.name),...(location.shops.length?['Shops']:[]),...(location.trees.length?['Berry trees']:[]),...(location.items.length?[`${location.items.length} ${location.items.length===1?'item':'items'}`]:[]),...(location.trainers.length?[`${location.trainers.length} trainers`]:[])].join(' · ')}</small></div><b aria-hidden="true">›</b></button>)}</div>
 {!matches.length&&<p className="resource-empty">No results.</p>}
 </>}
 </div>
}
