"""Export Emerald item icons with their in-game palettes and transparent backgrounds.
Usage: python tools/buildItemIcons.py /path/to/pokeemerald
"""
import json
import re
import sys
from pathlib import Path
from PIL import Image

source = Path(sys.argv[1])
root = Path(__file__).resolve().parent.parent
constants = (source / 'include/constants/items.h').read_text()
enum = re.search(r'enum\s*\{([\s\S]*?)\};', constants)[1]
enum = re.sub(r'/\*[\s\S]*?\*/|//[^\n]*', '', enum)
names = re.findall(r'\bITEM_(\w+)\b', enum)
ids = {name: index for index, name in enumerate(names)}
graphics = (source / 'src/data/graphics/items.h').read_text()
paths = dict(re.findall(r'const u32 (\w+)\[\]\s*=\s*INCGFX_U32\("([^"]+)"', graphics))
table = (source / 'src/data/item_icon_table.h').read_text()
output = root / 'public/items'
output.mkdir(exist_ok=True)
machines = {}
count = 0
for name, icon, palette in re.findall(r'\[ITEM_(\w+)\]\s*=\s*\{(\w+),\s*(\w+)\}', table):
    if name not in ids or icon not in paths or palette not in paths:
        continue
    image = Image.open(source / paths[icon])
    colors = [list(map(int, line.split())) for line in (source / paths[palette]).read_text().splitlines()[3:]]
    image.putpalette([channel for color in colors for channel in color])
    image.info['transparency'] = 0
    image.convert('RGBA').save(output / f'{ids[name]}.png')
    if re.fullmatch(r'(TM|HM)\d{2}', name):
        machines[name] = ids[name]
    count += 1
(root / 'src/data/itemIcons.js').write_text('// Original Emerald graphics from pret/pokeemerald; generated by tools/buildItemIcons.py\nexport const machineIconIds = ' + json.dumps(machines, indent=2) + '\n')
print(f'Exported {count} item icons, including {len(machines)} machines.')
