"""Generate Emerald cash-shop availability from a local pokeemerald checkout."""
from pathlib import Path
import json
import re
import sys
source=Path(sys.argv[1])
root=Path(__file__).resolve().parent.parent
constants=(source/'include/constants/items.h').read_text()
enum=re.search(r'enum\s*\{([\s\S]*?)\};',constants)[1]
enum=re.sub(r'/\*[\s\S]*?\*/|//[^\n]*','',enum)
ids={name:i for i,name in enumerate(re.findall(r'\bITEM_(\w+)\b',enum))}
machineNames=re.findall(r'^\s*F\((\w+)\)',(source/'include/constants/tms_hms.h').read_text(),re.M)
for index,name in enumerate(machineNames):
 code=('TM'+str(index+1).zfill(2)) if index<50 else ('HM'+str(index-49).zfill(2))
 ids[('TM_' if index<50 else 'HM_')+name]=ids[code]
itemSource=(source/'src/data/items.h').read_text()
machinePrices={}
for name,body in re.findall(r'\[ITEM_((?:TM|HM)_\w+)\]\s*=\s*\{([\s\S]*?)\n\s*\}',itemSource):
 if name in ids:
  machinePrices[ids[name]]=int(re.search(r'\.price\s*=\s*(\d+)',body)[1])
sold=set()
for file in (source/'data').rglob('*.inc'):
 text=file.read_text()
 for block in re.findall(r'((?:\s*\.2byte\s+ITEM_\w+\s*)+)\s*pokemartlistend',text):
  sold.update(ids[name] for name in re.findall(r'ITEM_(\w+)',block) if name in ids)
(root/'src/data/itemShopData.js').write_text('// Emerald cash-shop stock; generated by tools/buildItemShopData.py from pret/pokeemerald.\nexport const emeraldShopItems = new Set('+json.dumps(sorted(sold))+')\n')
exchange=(source/'data/maps/BattleFrontier_ExchangeServiceCorner/scripts.inc').read_text()
bp={ids[name]:int(cost) for cost,name in re.findall(r'setvar VAR_0x8008, (\d+)\s+setvar VAR_0x8009, ITEM_(\w+)',exchange)}
with (root/'src/data/itemShopData.js').open('a') as file:
 file.write('export const frontierItemPrices = '+json.dumps(bp,indent=2)+'\n')
 file.write('export const machineItemPrices = '+json.dumps(machinePrices,indent=2)+'\n')
print(f'{len(sold)} shop items and {len(bp)} BP prizes')
