"""Generate reachable wild held-item sources from pret Gen 3 checkouts.

Usage: python3 tools/generate-battle-item-wild-sources.py emerald ruby firered
The generated map IDs preserve the full source data for later display pruning.
"""
import json
import re
import sys
from pathlib import Path

ITEM_IDS = {179, 180, 183, 185, 186, 187, 188, 191, 192, 193, 196,
            198, 199, 200, 202, 203, 204, 205, 206, 207, 208, 209,
            210, 211, 212, 213, 214, 215, 216, 217, 219, 220, 221,
            222, 223, 224, 225}
misc = len(sys.argv) > 4 and sys.argv[4] == 'misc'
if misc:
    ITEM_IDS = {46,47,48,49,50,51,93,94,95,96,97,98,201,218,275,286,287,354,357,358,370,371,376}
utility = len(sys.argv) > 4 and sys.argv[4] == 'utility'
berries = len(sys.argv) > 4 and sys.argv[4] == 'berries'
if utility:
    ITEM_IDS = {195, 197, 111, 103, 104, 194, 110}
if berries:
    ITEM_IDS = set(range(133, 143)) | set(range(153, 159)) | set(range(168, 175))


def location(map_id):
    name = map_id.removeprefix('MAP_')
    name = re.sub(r'_(?:B?\d+F|ROOM\d*|NORTHWEST|NORTHEAST|SOUTHWEST|SOUTHEAST|NORTH|SOUTH|ENTRANCE|BACK|EXTERIOR)(?:_.*)?$', '', name)
    name = re.sub(r'_(?:LOW_TIDE|HIGH_TIDE).*$', '', name)
    name = re.sub(r'SAFARI_ZONE(?:_.*)?$', 'SAFARI_ZONE', name)
    name = re.sub(r'NEW_MAUVILLE(?:_.*)?$', 'NEW_MAUVILLE', name)
    name = re.sub(r'GRANITE_CAVE(?:_.*)?$', 'GRANITE_CAVE', name)
    name = re.sub(r'MT_PYRE(?:_.*)?$', 'MT_PYRE', name)
    name = re.sub(r'MT_EMBER(?:_.*)?$', 'MT_EMBER', name)
    name = re.sub(r'ROUTE(\d+)', r'ROUTE \1', name)
    return name.replace('_', ' ').title().replace('Mt ', 'Mt. ').replace('Pokemon', 'Pokémon')


rows = []
for root, games in zip(map(Path, sys.argv[1:]), [('Emerald',), ('Ruby', 'Sapphire'), ('FireRed', 'LeafGreen')]):
    constants = dict((key, int(value)) for key, value in re.findall(r'#define\s+(ITEM_\w+)\s+(\d+)\b', (root / 'include/constants/items.h').read_text()))
    if not constants:
        enum = (root / 'include/constants/items.h').read_text().split('enum {', 1)[1].split('};', 1)[0]
        enum = re.sub(r'//[^\n]*', '', enum)
        constants = {key: i for i, key in enumerate(re.findall(r'\bITEM_\w+\b', enum))}
    info_path = root / ('src/data/pokemon/base_stats.h' if games[0] == 'Ruby' else 'src/data/pokemon/species_info.h')
    species_items = {}
    for species, body in re.findall(r'\[(SPECIES_\w+)\]\s*=\s*\{(.*?)\n\s*\}', info_path.read_text(encoding='latin1'), re.S):
        common = re.search(r'\.(?:itemCommon|item1)\s*=\s*(ITEM_\w+)', body)
        rare = re.search(r'\.(?:itemRare|item2)\s*=\s*(ITEM_\w+)', body)
        if not common or not rare:
            continue
        common, rare = common[1], rare[1]
        held = [(common, 100)] if common == rare else [(common, 50), (rare, 5)]
        species_items[species] = [(constants[item], chance) for item, chance in held if constants.get(item) in ITEM_IDS]
    encounters = json.loads((root / 'src/data/wild_encounters.json').read_text())['wild_encounter_groups'][0]['encounters']
    for game in games:
        found = {}
        for area in encounters:
            map_id = area['map']
            if 'UNUSED' in map_id or 'ALTERING_CAVE' in map_id:
                continue
            if len(games) > 1 and not area['base_label'].endswith('_' + game):
                continue
            for method in ('land_mons', 'water_mons', 'fishing_mons', 'rock_smash_mons'):
                for mon in area.get(method, {}).get('mons', []):
                    for item, chance in species_items.get(mon['species'], []):
                        found.setdefault((item, mon['species'], chance), set()).add(map_id)
        for (item, species, chance), maps in sorted(found.items()):
            rows.append(dict(item=item, game=game, pokemon=species.removeprefix('SPECIES_').replace('_', ' ').title(),
                             chance=chance, locations=sorted({location(m) for m in maps}), maps=sorted(maps)))

# Merge games only when species, probability and every reachable map agree.
merged = []
for row in rows:
    match = next((r for r in merged if r['item'] == row['item'] and r['pokemon'] == row['pokemon'] and r['chance'] == row['chance'] and r['maps'] == row['maps']
                  and ((r['game'], row['game']) in [('Ruby', 'Sapphire'), ('FireRed', 'LeafGreen')])), None)
    if match:
        match['game'] += ' / ' + row['game']
    else:
        merged.append(row)

export_name = 'miscItemWildSources' if misc else 'berryItemWildSources' if berries else 'utilityItemWildSources' if utility else 'battleItemWildSources'
target = Path('src/data/' + export_name + '.js')
target.write_text('// Generated by tools/generate-battle-item-wild-sources.py from pret species and encounter data.\n'
                  '// Complete map IDs are retained even when locations share a display label.\n'
                  'export const ' + export_name + ' = ' + json.dumps(merged, ensure_ascii=False, indent=2) + '\n')
print(f'{len(merged)} wild species/game sources written to {target}')
